# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: garden.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'garden.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cgarden.proto\x12\x06garden\"\xb2\x04\n\tcontainer\x12\x13\n\theartbeat\x18\x01 \x01(\x05H\x00\x12\x31\n\x06update\x18\x02 \x01(\x0b\x32\x1f.garden.container.device_updateH\x00\x12>\n\x0bupdate_rqst\x18\x03 \x01(\x0b\x32\'.garden.container.device_update_requestH\x00\x1ak\n\rdevice_update\x12)\n\x06\x64\x65vice\x18\x01 \x01(\x0e\x32\x19.garden.container.devices\x12/\n\x06status\x18\x02 \x01(\x0e\x32\x1f.garden.container.device_status\x1a\x42\n\x15\x64\x65vice_update_request\x12)\n\x06\x64\x65vice\x18\x01 \x01(\x0e\x32\x19.garden.container.devices\"r\n\x07\x64\x65vices\x12\x0b\n\x07\x44\x45V_UNK\x10\x00\x12\x10\n\x0c\x44\x45V_ACT_PUMP\x10\x01\x12\x11\n\rDEV_ACT_VALVE\x10\x02\x12\x1a\n\x16\x44\x45V_SNS_WATER_LVL_HIGH\x10\x03\x12\x19\n\x15\x44\x45V_SNS_WATER_LVL_LOW\x10\x04\"l\n\rdevice_status\x12\x0c\n\x08STAT_UNK\x10\x00\x12\x0f\n\x0bSTAT_ACT_ON\x10\x01\x12\x10\n\x0cSTAT_ACT_OFF\x10\x02\x12\x13\n\x0fSTAT_SNS_ACTIVE\x10\x03\x12\x15\n\x11STAT_SNS_INACTIVE\x10\x04\x42\n\n\x08\x63ontentsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'garden_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONTAINER']._serialized_start=25
  _globals['_CONTAINER']._serialized_end=587
  _globals['_CONTAINER_DEVICE_UPDATE']._serialized_start=174
  _globals['_CONTAINER_DEVICE_UPDATE']._serialized_end=281
  _globals['_CONTAINER_DEVICE_UPDATE_REQUEST']._serialized_start=283
  _globals['_CONTAINER_DEVICE_UPDATE_REQUEST']._serialized_end=349
  _globals['_CONTAINER_DEVICES']._serialized_start=351
  _globals['_CONTAINER_DEVICES']._serialized_end=465
  _globals['_CONTAINER_DEVICE_STATUS']._serialized_start=467
  _globals['_CONTAINER_DEVICE_STATUS']._serialized_end=575
# @@protoc_insertion_point(module_scope)
