# Form implementation generated from reading ui file 'remote_gardener.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

# Imports
import sys
import time
import threading
import queue
import socket
import garden_pb2 as tool_shed
from google.protobuf.message import DecodeError
from datetime import timedelta
from datetime import datetime
from enum import Enum

# Set up thread safe queues
q_in = queue.Queue()
q_out = queue.Queue()
q_int = queue.Queue()

# Set up event for terminating threads
kill = threading.Event()

# Connection variables
s_lock = threading.Lock()
HOST = '192.168.1.178'
PORT = 50007
VERSION = '0.3'
ABOUT_STR = 'Remote Gardener v' + VERSION + ' created by Pablo Garcia Beltran (pablopgb.pgb@gmail.com)'
s = None

# Create device list:
devs = {
    tool_shed.container.devices.DEV_ACT_PUMP,
    tool_shed.container.devices.DEV_ACT_VALVE,
    tool_shed.container.devices.DEV_SNS_TANK_FULL,
    tool_shed.container.devices.DEV_SNS_TANK_EMPTY,
    tool_shed.container.devices.DEV_SNS_WELL_EMPTY,
    tool_shed.container.devices.DEV_SNS_RAIN,
}

##############################################################
# Thread that handles sending queued messages
def sender ():
    print( 'Sender thread is running' )

    while True:
        # Check to see if we should kill thread
        if kill.is_set():
            break

        try:
            container = q_out.get_nowait()
            data = container.SerializeToString()
            with s_lock:
                try:
                    if not container.HasField( 'get_device_updates' ):
                        print( 'Sending request:\n', container )
                    s.sendall( data )
                    time.sleep( 0.05 )

                except ConnectionAbortedError:
                    kill.set()
                    
                except ConnectionResetError:
                    kill.set()

        except queue.Empty:
            continue

# Create the sender thread
sender_thread = threading.Thread( target=sender, daemon=True )
##############################################################

##################################################################
# Thread that handles receiving responses
def receiver ():
    print( 'Receiver thread is running' )

    while True:
        # Check to see if we should kill thread
        if kill.is_set():
            break

        with s_lock:
            try:
                data = s.recv( 1024 )
                if data:
                    try:
                        container = tool_shed.container()
                        container.ParseFromString( data )
                        q_in.put( container )

                    except DecodeError:
                        print( 'Was not able to parse message!' )

            except BlockingIOError:
                continue

            except ConnectionAbortedError:
                kill.set()
                
            except ConnectionResetError:
                kill.set()

# Create the receiver thread
receiver_thread = threading.Thread( target=receiver, daemon=True )
##################################################################

####################################################################
# Thread that handles queueing the heartbeat
def heartbeat ():
    time.sleep( 1 )
    print( 'Heartbeat thread is running' )

    while True:
        # Check to see if we should kill thread
        if kill.is_set():
            break

        container = tool_shed.container()
        container.get_device_updates = 1
        q_out.put( container )
        time.sleep( 1 )

# Create the heartbeat thread
heartbeat_thread = threading.Thread( target=heartbeat, daemon=True )
####################################################################

# Create QtThread that will update the GUI
class UpdateMonitor ( QtCore.QThread ):
    device_update_signal = QtCore.pyqtSignal( [ int, bool ] )
    print_info_signal = QtCore.pyqtSignal( [ str ] )

    def run ( self ):
        while True:
            container = q_in.get()
            
            if container.HasField( 'all_device_updates' ):
                for dev_update in container.all_device_updates.updates:
                    self.device_update_signal.emit( dev_update.device, dev_update.status )

            elif container.HasField( 'next_watering_time' ):
                dt = datetime.fromtimestamp( container.next_watering_time.timestamp.seconds )
                td = timedelta( seconds=container.next_watering_time.duration.seconds )
                msg = 'Next watering scheduled for ' + str( td ) + ' at ' + str( dt ) + ', scheduled daily: ' + str( container.next_watering_time.daily )
                self.print_info_signal.emit( msg )

            elif container.HasField( 'all_watering_times' ):
                self.print_info_signal.emit( 'WATERING SCHEDULE:' )
                watering_times = [ x for x in container.all_watering_times.times ]
                watering_times.sort( key=lambda x:x.timestamp.seconds )
                for watering_time in watering_times:
                    dt = datetime.fromtimestamp( watering_time.timestamp.seconds )
                    td = timedelta( seconds=watering_time.duration.seconds )
                    msg = 'Watering scheduled for ' + str( td ) + ' at ' + str( dt ) + ', scheduled daily: ' + str( watering_time.daily )
                    self.print_info_signal.emit( msg )

            elif container.HasField( 'no_watering_times' ):
                self.print_info_signal.emit( 'No watering times scheduled!' )

            elif container.HasField( 'logs' ):
                if container.logs == '':
                    self.print_info_signal.emit( 'No logs!' )
                else:
                    self.print_info_signal.emit( 'LOGS:' )
                    self.print_info_signal.emit( container.logs[ :-1 ] )

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(669, 723)
        MainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Triangular)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_controls = QtWidgets.QWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_controls.sizePolicy().hasHeightForWidth())
        self.widget_controls.setSizePolicy(sizePolicy)
        self.widget_controls.setObjectName("widget_controls")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_controls)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gb_connection = QtWidgets.QGroupBox(parent=self.widget_controls)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_connection.sizePolicy().hasHeightForWidth())
        self.gb_connection.setSizePolicy(sizePolicy)
        self.gb_connection.setObjectName("gb_connection")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gb_connection)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lbl_host = QtWidgets.QLabel(parent=self.gb_connection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_host.sizePolicy().hasHeightForWidth())
        self.lbl_host.setSizePolicy(sizePolicy)
        self.lbl_host.setObjectName("lbl_host")
        self.gridLayout_2.addWidget(self.lbl_host, 0, 1, 1, 1)
        self.lbl_port = QtWidgets.QLabel(parent=self.gb_connection)
        self.lbl_port.setObjectName("lbl_port")
        self.gridLayout_2.addWidget(self.lbl_port, 2, 1, 1, 1)
        self.txt_port = QtWidgets.QLineEdit(parent=self.gb_connection)
        self.txt_port.setMaximumSize(QtCore.QSize(100, 16777215))
        self.txt_port.setText(str( PORT ))
        self.txt_port.setObjectName("txt_port")
        self.gridLayout_2.addWidget(self.txt_port, 2, 2, 1, 1)
        self.txt_host = QtWidgets.QLineEdit(parent=self.gb_connection)
        self.txt_host.setMaximumSize(QtCore.QSize(100, 16777215))
        self.txt_host.setText(HOST)
        self.txt_host.setObjectName("txt_host")
        self.gridLayout_2.addWidget(self.txt_host, 0, 2, 1, 1)
        self.btn_connect = QtWidgets.QPushButton(parent=self.gb_connection)
        self.btn_connect.setEnabled(True)
        self.btn_connect.setObjectName("btn_connect")
        self.gridLayout_2.addWidget(self.btn_connect, 3, 1, 1, 2)
        self.verticalLayout_3.addWidget(self.gb_connection)
        self.gb_watering = QtWidgets.QGroupBox(parent=self.widget_controls)
        self.gb_watering.setObjectName("gb_watering")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gb_watering)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gb_sched = QtWidgets.QGroupBox(parent=self.gb_watering)
        self.gb_sched.setObjectName("gb_sched")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.gb_sched)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_get_sched = QtWidgets.QPushButton(parent=self.gb_sched)
        self.btn_get_sched.setObjectName("btn_get_sched")
        self.verticalLayout_4.addWidget(self.btn_get_sched)
        self.line_6 = QtWidgets.QFrame(parent=self.gb_sched)
        self.line_6.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_4.addWidget(self.line_6)
        self.cb_sched_daily = QtWidgets.QCheckBox(parent=self.gb_sched)
        self.cb_sched_daily.setChecked(True)
        self.cb_sched_daily.setObjectName("cb_sched_daily")
        self.verticalLayout_4.addWidget(self.cb_sched_daily)
        self.de_sched = QtWidgets.QDateEdit(parent=self.gb_sched)
        self.de_sched.setObjectName("de_sched")
        self.verticalLayout_4.addWidget(self.de_sched)
        self.te_sched = QtWidgets.QTimeEdit(parent=self.gb_sched)
        self.te_sched.setObjectName("te_sched")
        self.verticalLayout_4.addWidget(self.te_sched)
        self.widget_2 = QtWidgets.QWidget(parent=self.gb_sched)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_sched_dur = QtWidgets.QLabel(parent=self.widget_2)
        self.lbl_sched_dur.setObjectName("lbl_sched_dur")
        self.horizontalLayout.addWidget(self.lbl_sched_dur)
        self.sb_sched_dur = QtWidgets.QSpinBox(parent=self.widget_2)
        self.sb_sched_dur.setMinimum(1)
        self.sb_sched_dur.setProperty("value", 1)
        self.sb_sched_dur.setObjectName("sb_sched_dur")
        self.horizontalLayout.addWidget(self.sb_sched_dur)
        self.lbl_sched_dur_units = QtWidgets.QLabel(parent=self.widget_2)
        self.lbl_sched_dur_units.setObjectName("lbl_sched_dur_units")
        self.horizontalLayout.addWidget(self.lbl_sched_dur_units)
        self.verticalLayout_4.addWidget(self.widget_2)
        self.btn_sched = QtWidgets.QPushButton(parent=self.gb_sched)
        self.btn_sched.setObjectName("btn_sched")
        self.verticalLayout_4.addWidget(self.btn_sched)
        self.btn_unsched = QtWidgets.QPushButton(parent=self.gb_sched)
        self.btn_unsched.setObjectName("btn_unsched")
        self.verticalLayout_4.addWidget(self.btn_unsched)
        self.verticalLayout_2.addWidget(self.gb_sched)
        self.widget_3 = QtWidgets.QWidget(parent=self.gb_watering)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_water_dur = QtWidgets.QLabel(parent=self.widget_3)
        self.lbl_water_dur.setObjectName("lbl_water_dur")
        self.horizontalLayout_2.addWidget(self.lbl_water_dur)
        self.sb_water_dur = QtWidgets.QSpinBox(parent=self.widget_3)
        self.sb_water_dur.setMinimum(1)
        self.sb_water_dur.setObjectName("sb_water_dur")
        self.horizontalLayout_2.addWidget(self.sb_water_dur)
        self.lbl_water_dur_units = QtWidgets.QLabel(parent=self.widget_3)
        self.lbl_water_dur_units.setObjectName("lbl_water_dur_units")
        self.horizontalLayout_2.addWidget(self.lbl_water_dur_units)
        self.cb_water_dur = QtWidgets.QCheckBox(parent=self.widget_3)
        self.cb_water_dur.setText("")
        self.cb_water_dur.setChecked(True)
        self.cb_water_dur.setObjectName("cb_water_dur")
        self.horizontalLayout_2.addWidget(self.cb_water_dur)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.btn_start_water = QtWidgets.QPushButton(parent=self.gb_watering)
        self.btn_start_water.setObjectName("btn_start_water")
        self.verticalLayout_2.addWidget(self.btn_start_water)
        self.btn_stop_water = QtWidgets.QPushButton(parent=self.gb_watering)
        self.btn_stop_water.setObjectName("btn_stop_water")
        self.verticalLayout_2.addWidget(self.btn_stop_water)
        self.verticalLayout_3.addWidget(self.gb_watering)
        self.gb_pumping = QtWidgets.QGroupBox(parent=self.widget_controls)
        self.gb_pumping.setObjectName("gb_pumping")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.gb_pumping)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_4 = QtWidgets.QWidget(parent=self.gb_pumping)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lbl_pump_dur = QtWidgets.QLabel(parent=self.widget_4)
        self.lbl_pump_dur.setObjectName("lbl_pump_dur")
        self.horizontalLayout_4.addWidget(self.lbl_pump_dur)
        self.sb_pump_dur = QtWidgets.QSpinBox(parent=self.widget_4)
        self.sb_pump_dur.setMinimum(1)
        self.sb_pump_dur.setProperty("value", 1)
        self.sb_pump_dur.setObjectName("sb_pump_dur")
        self.horizontalLayout_4.addWidget(self.sb_pump_dur)
        self.lbl_pump_dur_units = QtWidgets.QLabel(parent=self.widget_4)
        self.lbl_pump_dur_units.setObjectName("lbl_pump_dur_units")
        self.horizontalLayout_4.addWidget(self.lbl_pump_dur_units)
        self.cb_pump_dur = QtWidgets.QCheckBox(parent=self.widget_4)
        self.cb_pump_dur.setText("")
        self.cb_pump_dur.setChecked(True)
        self.cb_pump_dur.setObjectName("cb_pump_dur")
        self.horizontalLayout_4.addWidget(self.cb_pump_dur)
        self.verticalLayout_5.addWidget(self.widget_4)
        self.btn_start_pump = QtWidgets.QPushButton(parent=self.gb_pumping)
        self.btn_start_pump.setObjectName("btn_start_pump")
        self.verticalLayout_5.addWidget(self.btn_start_pump)
        self.btn_stop_pump = QtWidgets.QPushButton(parent=self.gb_pumping)
        self.btn_stop_pump.setObjectName("btn_stop_pump")
        self.verticalLayout_5.addWidget(self.btn_stop_pump)
        self.verticalLayout_3.addWidget(self.gb_pumping)
        self.gb_misc = QtWidgets.QGroupBox(parent=self.widget_controls)
        self.gb_misc.setObjectName("gb_misc")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.gb_misc)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.btn_log = QtWidgets.QPushButton(parent=self.gb_misc)
        self.btn_log.setObjectName("btn_log")
        self.verticalLayout_8.addWidget(self.btn_log)
        self.btn_about = QtWidgets.QPushButton(parent=self.gb_misc)
        self.btn_about.setObjectName("btn_about")
        self.verticalLayout_8.addWidget(self.btn_about)
        self.verticalLayout_3.addWidget(self.gb_misc)
        self.horizontalLayout_3.addWidget(self.widget_controls)
        self.widget_status = QtWidgets.QWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_status.sizePolicy().hasHeightForWidth())
        self.widget_status.setSizePolicy(sizePolicy)
        self.widget_status.setObjectName("widget_status")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_status)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gb_status = QtWidgets.QGroupBox(parent=self.widget_status)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_status.sizePolicy().hasHeightForWidth())
        self.gb_status.setSizePolicy(sizePolicy)
        self.gb_status.setObjectName("gb_status")
        self.gridLayout = QtWidgets.QGridLayout(self.gb_status)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(parent=self.gb_status)
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lbl_tank_empty = QtWidgets.QLabel(parent=self.widget)
        self.lbl_tank_empty.setObjectName("lbl_tank_empty")
        self.gridLayout_3.addWidget(self.lbl_tank_empty, 6, 0, 1, 1)
        self.lbl_pump_status_disp = QtWidgets.QLabel(parent=self.widget)
        self.lbl_pump_status_disp.setMinimumSize(QtCore.QSize(50, 0))
        self.lbl_pump_status_disp.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lbl_pump_status_disp.setObjectName("lbl_pump_status_disp")
        self.gridLayout_3.addWidget(self.lbl_pump_status_disp, 0, 1, 1, 1)
        self.line_4 = QtWidgets.QFrame(parent=self.widget)
        self.line_4.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_3.addWidget(self.line_4, 7, 0, 1, 2)
        self.lbl_valve_status = QtWidgets.QLabel(parent=self.widget)
        self.lbl_valve_status.setObjectName("lbl_valve_status")
        self.gridLayout_3.addWidget(self.lbl_valve_status, 2, 0, 1, 1)
        self.lbl_tank_empty_disp = QtWidgets.QLabel(parent=self.widget)
        self.lbl_tank_empty_disp.setMinimumSize(QtCore.QSize(50, 0))
        self.lbl_tank_empty_disp.setObjectName("lbl_tank_empty_disp")
        self.gridLayout_3.addWidget(self.lbl_tank_empty_disp, 6, 1, 1, 1)
        self.lbl_tank_full = QtWidgets.QLabel(parent=self.widget)
        self.lbl_tank_full.setObjectName("lbl_tank_full")
        self.gridLayout_3.addWidget(self.lbl_tank_full, 4, 0, 1, 1)
        self.line = QtWidgets.QFrame(parent=self.widget)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 1, 0, 1, 2)
        self.lbl_tank_full_disp = QtWidgets.QLabel(parent=self.widget)
        self.lbl_tank_full_disp.setMinimumSize(QtCore.QSize(50, 0))
        self.lbl_tank_full_disp.setObjectName("lbl_tank_full_disp")
        self.gridLayout_3.addWidget(self.lbl_tank_full_disp, 4, 1, 1, 1)
        self.line_3 = QtWidgets.QFrame(parent=self.widget)
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_3.addWidget(self.line_3, 5, 0, 1, 2)
        self.lbl_rain_disp = QtWidgets.QLabel(parent=self.widget)
        self.lbl_rain_disp.setMinimumSize(QtCore.QSize(50, 0))
        self.lbl_rain_disp.setObjectName("lbl_rain_disp")
        self.gridLayout_3.addWidget(self.lbl_rain_disp, 10, 1, 1, 1)
        self.lbl_well_empty_disp = QtWidgets.QLabel(parent=self.widget)
        self.lbl_well_empty_disp.setMinimumSize(QtCore.QSize(50, 0))
        self.lbl_well_empty_disp.setObjectName("lbl_well_empty_disp")
        self.gridLayout_3.addWidget(self.lbl_well_empty_disp, 8, 1, 1, 1)
        self.lbl_well_empty = QtWidgets.QLabel(parent=self.widget)
        self.lbl_well_empty.setObjectName("lbl_well_empty")
        self.gridLayout_3.addWidget(self.lbl_well_empty, 8, 0, 1, 1)
        self.lbl_valve_status_disp = QtWidgets.QLabel(parent=self.widget)
        self.lbl_valve_status_disp.setMinimumSize(QtCore.QSize(50, 0))
        self.lbl_valve_status_disp.setObjectName("lbl_valve_status_disp")
        self.gridLayout_3.addWidget(self.lbl_valve_status_disp, 2, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(parent=self.widget)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 3, 0, 1, 2)
        self.lbl_pump_status = QtWidgets.QLabel(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_pump_status.sizePolicy().hasHeightForWidth())
        self.lbl_pump_status.setSizePolicy(sizePolicy)
        self.lbl_pump_status.setObjectName("lbl_pump_status")
        self.gridLayout_3.addWidget(self.lbl_pump_status, 0, 0, 1, 1)
        self.lbl_rain = QtWidgets.QLabel(parent=self.widget)
        self.lbl_rain.setObjectName("lbl_rain")
        self.gridLayout_3.addWidget(self.lbl_rain, 10, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(parent=self.widget)
        self.line_5.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_3.addWidget(self.line_5, 9, 0, 1, 2)
        self.gridLayout.addWidget(self.widget, 1, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.gb_status)
        self.gb_output = QtWidgets.QGroupBox(parent=self.widget_status)
        self.gb_output.setObjectName("gb_output")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gb_output)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.gb_output)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 486, 463))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.text_output = QtWidgets.QTextEdit(parent=self.scrollAreaWidgetContents)
        self.text_output.setReadOnly(True)
        self.text_output.setObjectName("text_output")
        self.verticalLayout_7.addWidget(self.text_output)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.verticalLayout_6.addWidget(self.gb_output)
        self.horizontalLayout_3.addWidget(self.widget_status)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Create palettes used to color labels
        self.green = QtGui.QPalette()
        self.green.setColor( QtGui.QPalette.ColorRole.WindowText, QtGui.QColor( 'green' ) )
        self.red = QtGui.QPalette()
        self.red.setColor( QtGui.QPalette.ColorRole.WindowText, QtGui.QColor( 'red' ) )

        # Set up device to widget map
        self.dev_map = {
            tool_shed.container.devices.DEV_ACT_PUMP: ( self.lbl_pump_status, self.lbl_pump_status_disp ),
            tool_shed.container.devices.DEV_ACT_VALVE: ( self.lbl_valve_status, self.lbl_valve_status_disp ),
            tool_shed.container.devices.DEV_SNS_TANK_FULL: ( self.lbl_tank_full, self.lbl_tank_full_disp ),
            tool_shed.container.devices.DEV_SNS_TANK_EMPTY: ( self.lbl_tank_empty, self.lbl_tank_empty_disp ),
            tool_shed.container.devices.DEV_SNS_WELL_EMPTY: ( self.lbl_well_empty, self.lbl_well_empty_disp ),
            tool_shed.container.devices.DEV_SNS_RAIN: ( self.lbl_rain, self.lbl_rain_disp ),
        }

        # Initialize the time of day
        dt = datetime.today()
        date = QtCore.QDate()
        date.setDate( dt.year, dt.month, dt.day )
        time = QtCore.QTime()
        time.setHMS( dt.hour, dt.minute, dt.second, int( dt.microsecond / 1000 ) )
        self.de_sched.setDate( date )
        self.te_sched.setTime( time )

        # Disable the control interfaces until we have a connection
        self.gb_watering.setEnabled( False )
        self.gb_pumping.setEnabled( False )
        self.gb_status.setEnabled( False )
        self.btn_log.setEnabled( False )

        # Set up thread to signal updates to GUI
        self.updater = UpdateMonitor()
        self.updater.device_update_signal.connect( self.device_update )
        self.updater.print_info_signal.connect( self.text_output.append )
        self.updater.start()

        # Connect connect button to slot
        self.btn_connect.pressed.connect( self.connect )

        # Connect about button to slot
        self.btn_about.pressed.connect( self.about )

        # Connect get schedule button to slot
        self.btn_get_sched.pressed.connect( self.get_schedule )

        # Connect schedule watering button to slot
        self.btn_sched.pressed.connect( self.schedule_watering )

        # Connect unschedule watering button to slot
        self.btn_unsched.pressed.connect( self.unschedule_watering )

        # Connect start watering button to slot
        self.btn_start_water.pressed.connect( self.start_watering )

        # Connect stop watering button to slot
        self.btn_stop_water.pressed.connect( self.stop_watering )

        # Connect start pumping button to slot
        self.btn_start_pump.pressed.connect( self.start_pumping )

        # Connect stop pumping button to slot
        self.btn_stop_pump.pressed.connect( self.stop_pumping )

        # Connect peak event log button to slot
        self.btn_log.pressed.connect( self.peak_event_log )

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Remote Gardener"))
        self.gb_connection.setTitle(_translate("MainWindow", "Connection"))
        self.lbl_host.setText(_translate("MainWindow", "Host:"))
        self.lbl_port.setText(_translate("MainWindow", "Port:"))
        self.btn_connect.setText(_translate("MainWindow", "Connect"))
        self.gb_watering.setTitle(_translate("MainWindow", "Watering"))
        self.gb_sched.setTitle(_translate("MainWindow", "Scheduling"))
        self.btn_get_sched.setText(_translate("MainWindow", "Get Schedule"))
        self.cb_sched_daily.setText(_translate("MainWindow", "Daily"))
        self.lbl_sched_dur.setText(_translate("MainWindow", "Duration:"))
        self.lbl_sched_dur_units.setText(_translate("MainWindow", "min"))
        self.btn_sched.setText(_translate("MainWindow", "Schedule"))
        self.btn_unsched.setText(_translate("MainWindow", "Unschedule"))
        self.lbl_water_dur.setText(_translate("MainWindow", "Duration"))
        self.lbl_water_dur_units.setText(_translate("MainWindow", "min"))
        self.btn_start_water.setText(_translate("MainWindow", "Start"))
        self.btn_stop_water.setText(_translate("MainWindow", "Stop"))
        self.gb_pumping.setTitle(_translate("MainWindow", "Pumping"))
        self.lbl_pump_dur.setText(_translate("MainWindow", "Duration"))
        self.lbl_pump_dur_units.setText(_translate("MainWindow", "min"))
        self.btn_start_pump.setText(_translate("MainWindow", "Start"))
        self.btn_stop_pump.setText(_translate("MainWindow", "Stop"))
        self.gb_misc.setTitle(_translate("MainWindow", "Miscellaneous"))
        self.btn_log.setText(_translate("MainWindow", "Peak Event Log"))
        self.btn_about.setText(_translate("MainWindow", "About"))
        self.gb_status.setTitle(_translate("MainWindow", "Status"))
        self.lbl_tank_empty.setText(_translate("MainWindow", "Tank empty sensor status:"))
        self.lbl_pump_status_disp.setText(_translate("MainWindow", "UNKNOWN"))
        self.lbl_valve_status.setText(_translate("MainWindow", "Valve status:"))
        self.lbl_tank_empty_disp.setText(_translate("MainWindow", "UNKNOWN"))
        self.lbl_tank_full.setText(_translate("MainWindow", "Tank full sensor status:"))
        self.lbl_tank_full_disp.setText(_translate("MainWindow", "UNKNOWN"))
        self.lbl_rain_disp.setText(_translate("MainWindow", "UNKNOWN"))
        self.lbl_well_empty_disp.setText(_translate("MainWindow", "UNKNOWN"))
        self.lbl_well_empty.setText(_translate("MainWindow", "Well empty sensor status:"))
        self.lbl_valve_status_disp.setText(_translate("MainWindow", "UNKNOWN"))
        self.lbl_pump_status.setText(_translate("MainWindow", "Pump status:"))
        self.lbl_rain.setText(_translate("MainWindow", "Rain sensor status:"))
        self.gb_output.setTitle(_translate("MainWindow", "Output"))

    def device_update ( self, device, status ):
        self.dev_map[ device ][ 1 ].setText( 'ACTIVE' if status else 'INACTIVE' )
        if status:
            self.dev_map[ device ][ 1 ].setPalette( self.green )
        else:
            self.dev_map[ device ][ 1 ].setPalette( self.red )

    def connect ( self ):
        global s
        try:
            host = self.txt_host.text()
            port = int( self.txt_port.text() )
            s = socket.socket( socket.AF_INET, socket.SOCK_STREAM )
            s.settimeout( 0.5 )
            s.connect( ( host, port ) )
            s.settimeout( None )
            s.setblocking( 0 )

            # If none of that raised an exception then we connected
            self.gb_connection.setEnabled( False )
            self.gb_watering.setEnabled( True )
            self.gb_pumping.setEnabled( True )
            self.gb_status.setEnabled( True )
            self.btn_log.setEnabled( True )

            # Start comms threads
            sender_thread.start()
            receiver_thread.start()
            heartbeat_thread.start()

            # Print about string
            self.about()

            # Get device updates
            container = tool_shed.container()
            container.get_device_updates = 1
            q_out.put( container )

            # Get watering schedule
            container = tool_shed.container()
            container.get_watering_times = 1
            q_out.put( container )

        except ValueError:
            self.text_output.append( 'Port is not an integer' )

        except TimeoutError:
            self.text_output.append( 'Failed to connect to host' )

    def about ( self ):
        self.text_output.append( ABOUT_STR )

    def get_schedule ( self ):
        container = tool_shed.container()
        container.get_watering_times = 1
        q_out.put( container )

    def schedule_watering ( self ):
        daily = self.cb_sched_daily.isChecked()
        date = self.de_sched.date()
        time = self.te_sched.time()
        duration = self.sb_sched_dur.value()
        dt = datetime( year=date.year(), month=date.month(), day=date.day(), hour=time.hour(), minute=time.minute() )
        td = timedelta( minutes=duration )
        container = tool_shed.container()
        container.set_watering_time.timestamp.seconds = int( dt.timestamp() )
        container.set_watering_time.duration.FromTimedelta( td )
        container.set_watering_time.daily = daily
        q_out.put( container )
        self.get_schedule()

    def unschedule_watering ( self ):
        daily = self.cb_sched_daily.isChecked()
        date = self.de_sched.date()
        time = self.te_sched.time()
        duration = self.sb_sched_dur.value()
        dt = datetime( year=date.year(), month=date.month(), day=date.day(), hour=time.hour(), minute=time.minute() )
        td = timedelta( minutes=duration )
        container = tool_shed.container()
        container.cancel_watering_time.timestamp.seconds = int( dt.timestamp() )
        container.cancel_watering_time.duration.FromTimedelta( td )
        container.cancel_watering_time.daily = daily
        q_out.put( container )
        self.get_schedule()

    def start_watering ( self ):
        duration = self.sb_water_dur.value() if self.cb_water_dur.isChecked() else 0
        td = timedelta( minutes=duration )
        container = tool_shed.container()
        container.water_now.duration.FromTimedelta( td )
        q_out.put( container )

    def stop_watering ( self ):
        container = tool_shed.container()
        container.stop_watering = 1
        q_out.put( container )

    def start_pumping ( self ):
        duration = self.sb_pump_dur.value() if self.cb_pump_dur.isChecked() else 0
        td = timedelta( minutes=duration )
        container = tool_shed.container()
        container.pump_now.duration.FromTimedelta( td )
        q_out.put( container )

    def stop_pumping ( self ):
        container = tool_shed.container()
        container.stop_pumping = 1
        q_out.put( container )

    def peak_event_log ( self ):
        container = tool_shed.container()
        container.peak_event_log = 10
        q_out.put( container )


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
