on: [push]

jobs:
  pyinstaller-win-build:
    permissions:
      contents: write
    runs-on: windows-latest
    name: Create Windows Executable
    steps:
      - uses: Martin005/pyinstaller-action@v1.2.0
        with:
          spec: 'remote_gardener_gui.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'remote_gardener'
          options: --onefile, --windowed, --name "Remote Gardener",
      - uses: actions/upload-artifact@v4
        with:
          name: remote_gardener
          path: ./dist
      - uses: actions/download-artifact@v4
        with:
          name: remote_gardener
          path: ./dist
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated Change
          branch: main
          commit_options: '--no-verify --signoff'
          commit_author: Author <actions@github.com>
          status_options: '--untracked-files=no'
          skip_dirty_check: true

  pyinstaller-mac-build:
    permissions:
      contents: write
    runs-on: macos-13
    name: Create Mac OS Executable
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      - uses: Martin005/pyinstaller-action@v1.2.0
        with:
          spec: 'remote_gardener_gui.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'remote_gardener'
          options: --onefile, --windowed, --name "Remote Gardener",
      - uses: actions/upload-artifact@v4
        with:
          name: remote_gardener
          path: ./dist
      - uses: actions/download-artifact@v4
        with:
          name: remote_gardener
          path: ./dist
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated Change
          branch: main
          commit_options: '--no-verify --signoff'
          commit_author: Author <actions@github.com>
          status_options: '--untracked-files=no'
          skip_dirty_check: true
